name: Simple Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
        
    - name: Execute API tests
      run: |
        docker run \
          -v ./data:/app/data \
          -v ./output:/app/output \
          itbusina/apibee:latest \
            -c data/collection.json \
            -p \
            -o output \
            -l $license

    - name: Archive output results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: report
        path: ./output/
